[[edge_functions]]
path = "/api/auth/signup"
function = "auth/signup.ts"

[[edge_functions]]
path = "/api/auth/login"
function = "auth/login.ts"

[[edge_functions]]
path = "/api/user/create"
function = "user/create.ts"

[[edge_functions]]
path = "/api/user/update"
function = "user/update.ts"

[[edge_functions]]
path = "/api/user/get"
function = "user/get.ts"

[[edge_functions]]
path = "/api/user/dashboard"
function = "user/dashboard.ts"

[[edge_functions]]
path = "/api/user/preferences"
function = "user/update-preferences.ts"

[[edge_functions]]
path = "/api/user/favorites/business"
function = "user/favorites-business.ts"

[[edge_functions]]
path = "/api/user/favorites/coupon"
function = "user/favorites-coupon.ts"

[[edge_functions]]
path = "/api/user/favorites"
function = "user/favorites-get.ts"