name: E2E Tests (Playwright)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps
        run: npm ci

      - name: Install web deps
        run: npm ci
        working-directory: apps/web

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1

      - name: Start web dev server (mock mode)
        env:
          VITE_SUPABASE_URL: https://forfgrnhuyihycfuwpze.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcmZncm5odXlpaHljZnV3cHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTA3NzQsImV4cCI6MjA2ODc2Njc3NH0.NyKhvEQXicWmjq_cNWU_d3t53pg9Q9X6KHipT5PxgeU
          VITE_E2E_MOCK: '1'
        run: |
          nohup npm run dev --silent --prefix apps/web >/dev/null 2>&1 &
          for i in {1..60}; do
            if curl -sSf http://localhost:5173 > /dev/null; then
              echo "Web server is up"
              break
            fi
            echo "Waiting for Vite dev server... ($i)"
            sleep 1
          done

      - name: Run Playwright E2E (Chromium)
        run: npx playwright test --project=chromium -c e2e/playwright.noserver.config.ts --reporter=html

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

